(() => {
  function createState({ getDefaultCustomScaleIntervals = () => [] } = {}) {
    return {
      audioContext: null,
      stream: null,
      processedStream: null,
      analyser: null,
      gainNode: null,
      monitorGain: null,
      beatSourceNode: null,
      beatGainNode: null,
      monitorConnected: false,
      monitorMode: null,
      nativeMonitorActive: false,
      recorderDestination: null,
      mediaRecorder: null,
      chunks: [],
      isRecording: false,
      recordStart: 0,
      recordStartPosition: 0,
      recordLatencyMs: 0,
      lastInputDb: -Infinity,
      lastSignalAt: 0,
      lastHealthRenderAt: 0,
      timerFrame: 0,
      waveFrame: 0,
      recordWaveform: [],
      latestTake: null,
      activeView: "record",
      armedTrackId: "main",
      trackFolderCollapsed: {
        lead: false,
        adlibs: false,
        hook: false,
      },
      selectedPresetId: "trap-hard",
      selectedVocalTakeId: null,
      isAnalyzingVocal: false,
      isBatchRendering: false,
      beatUrl: "",
      beatArrayBuffer: null,
      beatFileName: "",
      mimeType: "",
      inputGain: 1.25,
      beatGain: 1.4,
      audioInputDeviceId: "",
      audioOutputDeviceId: "",
      nativeBufferSize: 128,
      monitorEnabled: false,
      isExportingMix: false,
      isExportingAssets: false,
      isExportQueueRunning: false,
      exportQueue: [],
      exportJobSeq: 1,
      exportPreviewAudio: null,
      lastExportNormalizeGain: 1,
      lastExportLoudnessGain: 1,
      isAnalyzingLoudness: false,
      loudnessReport: null,
      isRenderingVocal: false,
      autosaveTimer: 0,
      isAutosaving: false,
      lastBackupAt: 0,
      hasAutosave: false,
      backupHistory: [],
      currentTakeAudio: null,
      currentTakeId: null,
      currentTakeResolve: null,
      pluginScanResult: null,
      loadedProjectEnvironment: null,
      loadedProjectExportHistory: [],
      isPluginScanning: false,
      isRefreshingNativeStats: false,
      isQueuePlaying: false,
      queueMode: "all",
      queueTakeIds: [],
      queueIndex: -1,
      isSessionPlaying: false,
      sessionOrigin: 0,
      sessionStartedAt: 0,
      sessionEndTimer: 0,
      sessionTimers: [],
      sessionPlayers: [],
      sessionPlayingTakeIds: new Set(),
      timelineCursor: 0,
      punchEnabled: false,
      loopEnabled: false,
      metronomeEnabled: false,
      metronomeTimer: 0,
      metronomeBeat: 0,
      isCountInActive: false,
      countInToken: 0,
      punchIn: 0,
      punchOut: 4,
      punchTimers: [],
      isPunchWaiting: false,
      isPunchRecording: false,
      isLoopRecording: false,
      currentLoopCycle: false,
      loopRecordTakeCount: 0,
      markers: [
        { id: "marker-intro", type: "Intro", time: 0 },
        { id: "marker-verse", type: "Verse", time: 16 },
        { id: "marker-hook", type: "Hook", time: 48 },
      ],
      customScaleIntervals: getDefaultCustomScaleIntervals(),
      selectedTimelineTakeId: null,
      timelineRegionDrag: null,
      timelineUndoStack: [],
      timelineRedoStack: [],
    };
  }

  function createTracks() {
    return [
      { id: "main", name: "Main", color: "#c8ff4d", volume: 0.9, pan: 0, muted: false, solo: false, takes: [] },
      { id: "double", name: "Double", color: "#41e6d0", volume: 0.72, pan: 0, muted: false, solo: false, takes: [] },
      { id: "adlib-l", name: "Adlib L", color: "#ffb74a", volume: 0.68, pan: -0.45, muted: false, solo: false, takes: [] },
      { id: "adlib-r", name: "Adlib R", color: "#7db2ff", volume: 0.68, pan: 0.45, muted: false, solo: false, takes: [] },
      { id: "hook", name: "Hook", color: "#ff4f64", volume: 0.82, pan: 0, muted: false, solo: false, takes: [] },
    ];
  }

  function createTrackFolders() {
    return [
      { id: "lead", name: "Lead stack", trackIds: ["main", "double"], color: "#c8ff4d" },
      { id: "adlibs", name: "Adlib stack", trackIds: ["adlib-l", "adlib-r"], color: "#ffb74a" },
      { id: "hook", name: "Hook stack", trackIds: ["hook"], color: "#ff4f64" },
    ];
  }

  function createPresets() {
    return [
      { id: "trap-hard", name: "Trap Hard", retune: 88, humanize: 10, vibrato: 42, formant: 10, gate: 18, deEss: 28, comp: 72, saturation: 38, space: 18, width: 42 },
      { id: "drill-dark", name: "Drill Dark", retune: 72, humanize: 18, vibrato: 38, formant: -12, gate: 24, deEss: 34, comp: 82, saturation: 46, space: 12, width: 28 },
      { id: "clean-rap", name: "Clean Rap", retune: 22, humanize: 60, vibrato: 72, formant: 0, gate: 10, deEss: 20, comp: 62, saturation: 18, space: 8, width: 18 },
      { id: "rage-wide", name: "Rage Wide", retune: 95, humanize: 5, vibrato: 30, formant: 18, gate: 16, deEss: 38, comp: 76, saturation: 58, space: 34, width: 86 },
      { id: "radio-hook", name: "Radio Hook", retune: 58, humanize: 30, vibrato: 64, formant: 8, gate: 12, deEss: 30, comp: 68, saturation: 32, space: 45, width: 72 },
      { id: "lofi-demo", name: "Lo-Fi Demo", retune: 36, humanize: 55, vibrato: 78, formant: -18, gate: 4, deEss: 14, comp: 54, saturation: 62, space: 22, width: 12 },
    ];
  }

  window.PunchLabStudioState = {
    createPresets,
    createState,
    createTrackFolders,
    createTracks,
  };
})();
